### PR TITLE
Styles/dashboard

### PR DESCRIPTION
**Pull request by b1u3too**
Hey pals! No rush, hope you're resting well. 

Have made some tweaks just to the dashboard layout to help us get ready for stylin'. When all loaded up, our bebe should now look like this: 
image

Toddling off to have a little fun in Corel Painter with that beauty logo inspiration Matt was working with earlier, talk to y'all tomorrow! :)

### CODE REVIEW

**Comment by b1u3too** [comment]
(Darned if I still haven't figured out how to get that background image loading, but I 'spose that can hold on a little longer yet!)

**Review by MGS31 — APPROVED** [review]
Hey looks awesome! love the gradients and the favourite addition button! Are we changing the nav to be dark or sticking with the white background we had in the figjam?

**Review by rachelpr — COMMENTED** [review]
same question with matt! I'd prefer to leave it white since it adds some contrast to the navbar and makes the icons pop!

Also a little confused where all the forecast went :/ 

BUT the favourites button looks siiiiick!

**Comment by b1u3too** [comment]
> Hey looks awesome! love the gradients and the favourite addition button! Are we changing the nav to be dark or sticking with the white background we had in the figjam?

In the mockup the color was just a bit transparent! The styling is white, but 50% opacity right now. The darker gray is just temporary until I figure out how to get the darned background image loading. Can absolutely swap it back! to just a white background!

**Comment by b1u3too** [comment]
> same question with matt! I'd prefer to leave it white since it adds some contrast to the navbar and makes the icons pop!
> 
> Also a little confused where all the forecast went :/
> 
> BUT the favourites button looks siiiiick!

Aw thanks! Can absolutely remove that temporary dark background color and crank up the opacity on the navbar a smidge. 
And oh spit, my tiredbrain didn't even notice the forecast didn't load -- On a break I can hop over and interrogate that a bit more!

**Comment by rachelpr** [comment]
Screen Shot 2022-08-09 at 3 01 04 PM

Looks like the forecast is there! So I'm good to approve this and we can discuss navbar changes later !

**Review by rachelpr — APPROVED** [review]

**Pull request merged**
