### PR TITLE
Feature/connect fav to search

### PR DESCRIPTION
**Pull request by b1u3too**
Howdy Pals! 
0 rush, this is the promised hookup from favourites to rendering each of the dashboards for our respective cities. 
Toward the end I also fixed up a couple of the UI things we discussed during today's call, adjusting spacing and the logged-in user's display, which looks a little bit like this right now: 
image

Feedback absolutely welcome! Promise to push the last of my meddlesome UI tinkering today, so we have time to discuss/accept/reject tomorrow. :)

### CODE REVIEW

**Review by MGS31 — APPROVED** [review]
looks solid!

**Comment by b1u3too** [comment]
> looks solid!

Thanks! 
I backtracked from UI updates and found that the home button not clearing search here either. I just pushed a small change that should fix that now, feel free to take it for a spin!

**Comment by MGS31** [comment]
> > looks solid!
> 
> Thanks! I backtracked from UI updates and found that the home button not clearing search here either. I just pushed a small change that should fix that now, feel free to take it for a spin!

So functionality looks great! but only seems to work when selecting a favourite? Hate to be that a hat but would it be possible to also include this for general search? 

I think this would be the last thing we need to revise to get it like PERFECT!

**Comment by b1u3too** [comment]
> > > looks solid!
> > 
> > 
> > Thanks! I backtracked from UI updates and found that the home button not clearing search here either. I just pushed a small change that should fix that now, feel free to take it for a spin!
> 
> So functionality looks great! but only seems to work when selecting a favourite? Hate to be that a hat but would it be possible to also include this for general search?
> 
> I think this would be the last thing we need to revise to get it like PERFECT!

Have you pulled down since those last two commits? The last two have now tweaked the home button to clear the search regardless of whether they accessed a dashboard from their favourites or the searchbar directly. :)

**Comment by rachelpr** [comment]
Screen Shot 2022-08-14 at 8 46 13 PM

It appears we have a dark mode?! 🚀 

Looks solid! Tested clearing the search bar from a favourite, or from a search and its working for me!

**Review by rachelpr — APPROVED** [review]

**Pull request merged**
