### PR TITLE
Validate express connection to frontend

### PR DESCRIPTION
**Pull request by rachelpr**

### CODE REVIEW

**Comment by rachelpr** [comment]
does this look good? 🤔

**Comment by MGS31** [comment]
Great Work, I like the validations you put forth for this work.

**Comment by b1u3too** [comment]
Look very valid!

**Review by MGS31 — APPROVED** [review]
Looks FANTABOULOUS! Love it Rachel amazing good work.

**Review by b1u3too — APPROVED** [review]

**Review by MGS31 — APPROVED** [review]
I ALREADY DID THIS IT:S GOOD

**Pull request merged**
